require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - 'bin/*'
    - 'cloud/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.1
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true
