########################################################################
#                                                                      #
#                                                                      #
#                         Custom Gems                                  #
#                                                                      #
#                                                                      #
########################################################################

gem "devise"
gem "io-wait", "0.2.0"
gem "puma", "6.4.2"
gem "rackup", "~> 2.2"
gem "rubocop-rails", "~> 2.22"
gem "whenever", require: false

group :development, :test do
  gem "annotate"
  gem "brakeman"
  gem "bundler-audit"
  gem "factory_bot_rails"
  gem "guard"
  gem "guard-brakeman"
  gem "guard-minitest"
  gem "guard-reek"
  gem "guard-rspec"
  gem "guard-rubocop"
  gem "pry-byebug"
  gem "reek"
  gem "rubocop", require: false
  gem "rubocop-capybara"
  gem "rubocop-factory_bot"
  gem "rubocop-git"
  gem "rubocop-performance"
  gem "rubocop-rake"
  gem "rubocop-rspec"
end

group :development do
  gem "foreman"
end

group :test do
  gem "faker"
  gem "rack-app", "~> 11.0"
  gem "rspec-rails"
  gem "simplecov"
end
